input_beam:
  style: distgen     # from_file or distgen
  #distgen_input_file: /sdf/group/ad/beamphysics/jytang/pyDFCSR/pyDFCSR_2D/example/input/chicane_init_beam.yaml
  distgen_input_file: input/chicane_init_beam.yaml

input_lattice:
  #lattice_input_file: /sdf/group/ad/beamphysics/jytang/pyDFCSR/pyDFCSR_2D/example/input/chicane_lattice.yaml
  lattice_input_file: input/chicane_lattice.yaml

particle_deposition:
  pbins: 300         # number of grids in x for particle deposition
  obins: 300         # number of grids in y for particle deposition
  plim:  5           # range in x in the unit of sigma_x
  olim: 5            # range in z in the unit of sigma_z
  filter_order: 1    # 0 for no filter
  filter_window: 9
  velocity_threshold : 1000
  #upper_limit: 2000   # upper limit for interpolation

CSR_integration:
  n_formation_length: 1
  zbins: 200
  xbins: 200

CSR_computation:
  compute_CSR: 1                # if zero, only track the beam
  apply_CSR: 1                   # flag apply CSR to particles
  transverse_on: 1               # flag include transverse wake
  pbins: 10                    # The mesh on which CSR wake is computed
  obins: 30
  plim: 3
  olim: 3
  write_beam: [16, 17, 18, 19, 24, 25, 26, 32, 33,34, 35, 46,47,48,49,50]
  write_wakes: True
  write_name: 'chicane'
  #workdir: '/sdf/data/ad/ard/u/jytang/pyDFCSR/chicane_output/'
  workdir: './output'














